//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSON2CSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSON2CSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 String.prototype.format = function () {
        ///    var args = arguments;
        ///    return this.replace(/\{(\d+)\}/g,
        ///				function (m, i) {
        ///				    return args[i];
        ///				});
        ///}
        ///
        ///String.prototype.trim = function () {
        ///    return this.replace(/(^\s*)|(\s*$)/g, &quot;&quot;);
        ///}
        ///
        ///JSON2CSharp = {
        ///    _allClass: [],
        ///    _genClassCode: function (obj, name) {
        ///        var clas = &quot;public class {0}\r\n{\r\n&quot;.format(name || &quot;Root&quot;);
        ///        for (var n in obj) {
        ///            var v = obj[n];
        ///            n = n.trim();
        ///            c [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string JSON2CSharp {
            get {
                return ResourceManager.GetString("JSON2CSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 function JSONFormat(txt, compress) { /* 格式化JSON源码(对象转换为JSON文本) */
        ///				var indentChar = &apos;    &apos;;
        ///				if(/^\s*$/.test(txt)) {
        ///					return &apos;数据为空,无法格式化! &apos;;
        ///				}
        ///				try {
        ///					var data = eval(&apos;(&apos; + txt + &apos;)&apos;);
        ///				} catch(e) {
        ///					return &apos;数据源语法错误,格式化失败! &apos;;
        ///				};
        ///				var draw = [],
        ///					last = false,
        ///					This = this,
        ///					line = compress ? &apos;&apos; : &apos;\n&apos;,
        ///					nodeCount = 0,
        ///					maxDepth = 0;
        ///
        ///				var notify = function(name, value, isLast, indent /*缩进*/ , formObj) {
        ///					nodeCount++; /*节点计数*/
        ///	 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string JSONFormat {
            get {
                return ResourceManager.GetString("JSONFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Roboto_Medium {
            get {
                object obj = ResourceManager.GetObject("Roboto_Medium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Roboto_Regular {
            get {
                object obj = ResourceManager.GetObject("Roboto_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
